version: "3"
services:
  sso:
    image: registry.access.redhat.com/redhat-sso-7/sso72-openshift
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS_APPEND="-Dkeycloak.profile=preview"
      - SSO_ADMIN_USERNAME=user 
      - SSO_ADMIN_PASSWORD=password
  server:
    ports:
      - 8081:4567
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - APP_PORT=8081
    volumes:
      - ./views:/opt/tiny-rhsso-oauth-app/views
      - ${PWD}/server.rb:/opt/tiny-rhsso-oauth-app/server.rb
      - ${PWD}/seed_script.rb:/opt/tiny-rhsso-oauth-app/seed_script.rb